### ISSUE TITLE
bloom Website Down?

### ISSUE THREAD

**Issue by lkoepsel** [bloombloombloom/Bloom#104]
Hi,
I've been attempting to get to your website for a few weeks and it appears down. 

Is bloom.oscillate.io down?

Thanks!
Lief

**Comment by navnavnav** [comment]
Hey Lief,

I'm very sorry about this. The website works fine for me, and looking at the server logs, it's also working for others, so I'm not entirely sure what's happened here, but my guess is that you've been caught up in a blanket ban that I've had to resort to lately.

Long story short: back in December, I placed a protest banner on the website. Some time after that, I began to notice some bad actors attempting to breach the server. I decided to employ the "sledge-hammer approach" and firewall off entire ISPs that were facilitating the attacks. I suspect you may have gotten caught up in this.

Could you please share the name of the ISP you're currently using? I will update my firewall rules accordingly.

Thanks,

**Comment by navnavnav** [comment]
Thanks for that, Lief.

I've found a firewall rule that was indeed blocking your IP address. I've just removed it - could you please try again? Please let me know if it works.

Thanks,

**Comment by lkoepsel** [comment]
Yes, it works!

And I empathize, words fail me as to what is happening. 

Thank you,
LIef

**Comment by navnavnav** [comment]
Excellent, thanks for confirming!

BTW I pushed the first major release, v1.0.0, in September. Lot's of cool new stuff: https://github.com/bloombloombloom/Bloom/releases/tag/v1.0.0

As it was a major release there are some small changes needed to migrate old projects over. More details can be found at: https://github.com/bloombloombloom/Bloom/discussions/89

If you do decide to give it a try, please let me know if you have any questions 😄 

Will close this now 👍🏽
