### ISSUE TITLE
TCA0 not listed on Insight for ATtiny412

### ISSUE THREAD

**Issue by ashlynblack** [bloombloombloom/Bloom#113]
Issue reported via Bloom Insight.
Target name: ATtiny412
Target ID: 0x1e9223
Target variant: ATtiny412-SSFR

Please describe your issue below. Include as much detail as possible.

There is no register listing for TCA0 on Insight. TCB0 and TCD0 are listed but TCA0 is not.

**Comment by ashlynblack** [comment]
Just seen the other issues for TCA0, can close this if you want.

**Comment by navnavnav** [comment]
Closed this as a duplicate of https://github.com/bloombloombloom/Bloom/issues/111
