### ISSUE TITLE
Support for the MPLAB ICE 4

### ISSUE THREAD

**Issue by navnavnav** [bloombloombloom/Bloom#31]
I hope to purchase one of these at some point (but not sure when). It would be nice if Bloom could support it.

I will keep this ticket updated with any developments.

**Comment by xedbg** [comment]
FYI: ICE4 is not "EDBG-based" so all bets are off with regard to the protocol, so expect to have to do a fair amount of work to get it in.

**Comment by navnavnav** [comment]
Thanks for letting me know, @xedbg 

Do you know when/if Microchip plan on publishing any documents RE the protocols employed by the ICE 4? I won't be able to support it without some documentation. Anything similar to the "EDBG-based Tools Protocols" document would be excellent.

**Comment by xedbg** [comment]
I can ask around... (but PICkit4 and Snap are part of that protocol-group and those are not public [yet])

**Comment by xedbg** [comment]
The short answer is: ICE 4 actually _does_ use the same EDBG-based stack for supporting AVR devices over a USB connection, so the same code supporting PICkit4 and Snap should in theory work for ICE4
The longer answer is: its complicated - this may be a short/medium-term solution, and at some point the interface may be changed.  There are currently no concrete plans to publish that protocol spec, but that too may change in the longer-term.  These units are also well above the price bracket for "giveaways", so for your purposes - any hardware investment which expects an EDBG-like interface has a fair amount of risk attached, I'm afraid.

**Comment by navnavnav** [comment]
Thanks for letting me know @xedbg.

I will hold off on this for now, seeing as no one has requested it.
