### ISSUE TITLE
Unable to build master (ba3152b)

### ISSUE THREAD

**Issue by mattbucknall** [bloombloombloom/Bloom#71]
Unable to compile due to missing header files (Linux, gcc 12.2.1).

src/ProjectConfig.hpp is missing `#include <optional>`

src/DebugToolDrivers/Protocols/CMSIS-DAP/VendorSpecific/EDBG/Edbg.hpp is missing `#include <cstddef>`

**Comment by navnavnav** [comment]
Have you tried building from the develop branch? Those errors started appearing in more recent compiler versions (G++11+), but have been addressed in the develop branch.

[Building from develop should be a little easier, also.](https://github.com/bloombloombloom/Bloom/discussions/69)

**Comment by mattbucknall** [comment]
Develop branch builds fine, thanks.
