### ISSUE TITLE
Remove generic `avr8` target name 

### ISSUE THREAD

**Issue by navnavnav** [bloombloombloom/Bloom#72]
The generic `avr8` target name is resulting in additional complexity in Bloom's codebase. It works by using the target's signature to identify the target, but some physical interfaces do not allow us to read the target signature until we've set some target-specific parameters on the EDBG debug tool, and some targets have the same signature. This means, for many cases, it doesn't work at all.

Getting rid of it will allow me to simplify the codebase, so that's what I'm going to do.

I understand that this is a breaking change, which is why it will be released as part of v1.0.0, which will likely come after v0.12.0 or v0.13.0.

In the meantime, Bloom will present a deprecation notice to anyone still using it from v0.12.0 and onwards.

**Comment by septatrix** [comment]
You can can introduce breaking changes in 0.x releases while still being in accordance with SemVer. Might make sense to release it as a 0.x version depending on how strong you feel about the current API and releasing a 1.0 version
